### ISSUE TITLE
Both currently supported authentication protocols are deprecated

### ISSUE THREAD

**Issue by alexjeen** [php-twinfield/twinfield#35] opened 2017-12-24 20:09 UTC
Twinfield offers OpenID now and the other methods (password and OAuth v1.0) are now deprecated. End of life is somewhere in 2018. Right now it also uses a LoginService to retrieve the session. When using OAuth 2.0 this is also not needed anymore. Also the OAuth v1.0 version is really poorly written (uses Javascript for a redirect)

The library will need to refactored significantly to provide the changes for OAuth.  I propose keeping version 1.0 backwards compatible and leaving in the old authentication ways.

In 2.0 release, we should remove all the old mechanismes and implement OAuth:

https://c3.twinfield.com/webservices/documentation/#/ApiReference/Authentication/OpenIdConnect#General-information

I propose using thephpleageu/oauth2/client library for this:

https://github.com/thephpleague/oauth2-client

**Comment by alexjeen** [comment] 2017-12-24 20:09
By the way I have already did this but need to find some time to integrate it into this library.

**Comment by willemstuursma** [comment] 2017-12-27 07:45
Hi @alexjeen. Thanks for bringing this up. We'll definitely support a pull request to get such changes in. Using `thephpleageu/oauth2-client` sounds like a great idea. 

I'll keep this issue open until the problem is resolved.

**Comment by anand007pandey** [comment] 2018-01-08 09:07
Hi @alexjeen. Can you please help me i dont find where is the secret key and id found in twinfield app. Please give me the option or screenshot where it will find? Thanks in advance.

**Comment by alexjeen** [comment] 2018-01-08 09:13
Must request it through their website:

https://taxnl.wolterskluwer.com/software-koppelingen/partner-worden/openid-connect-request/

**Comment by anand007pandey** [comment] 2018-01-08 09:43
Thanks for help but i already register with twinfield by this link

**Comment by anand007pandey** [comment] 2018-01-10 13:43
public function login(\Illuminate\Http\Request $request) {
        $clientID = $request->get('clientID');
        $clientSecret = $request->get('clientSecret');
        $returnURL = $request->get('returnURL');
        $Organization = $request->get('Organization');
        
        $config = new \PhpTwinfield\Secure\Config();
        $config->setOAuthParameters($clientID, $clientSecret, $returnURL, $Organization, true);
        $connection = new \PhpTwinfield\Secure\Connection($config);
        
        print_r($connection);
}

it gives me error =>  sorry,temp_token not set
Please help me how can i get the access token.

**Comment by willemstuursma** [comment] 2018-02-09 13:59
This will be resolved in #75.

**Closed by willemstuursma** 2018-02-09 13:59 UTC
Labels: enhancement
